"""initial schema

Revision ID: 9411b135d809
Revises: 
Create Date: 2026-09-18 19:15:30.843710

"""
import sqlalchemy as sa

import app.models
from alembic import op

revision = '9411b135d809'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('starts_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('tz_label', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('host', sa.String(length=160), nullable=False),
    sa.Column('image_key', sa.String(length=200), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_codes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_codes_email'), 'login_codes', ['email'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role_company', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('working_on', sa.Text(), nullable=False),
    sa.Column('why_join', sa.Text(), nullable=False),
    sa.Column('referrer', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('suggest_gathering', sa.Boolean(), nullable=False),
    sa.Column('decided_by_id', sa.String(length=32), nullable=True),
    sa.Column('decided_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_email'), 'applications', ['email'], unique=False)
    op.create_index(op.f('ix_applications_referrer'), 'applications', ['referrer'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=40), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('private_notes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_notes_subject_id'), 'private_notes', ['subject_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('organization', sa.String(length=120), nullable=False),
    sa.Column('working_on', sa.Text(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('expertise', sa.JSON(), nullable=False),
    sa.Column('come_to_me_for', sa.Text(), nullable=False),
    sa.Column('like_to_meet', sa.Text(), nullable=False),
    sa.Column('outside_ai', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=False),
    sa.Column('linkedin', sa.String(length=300), nullable=False),
    sa.Column('contact_links', sa.JSON(), nullable=False),
    sa.Column('show_email', sa.Boolean(), nullable=False),
    sa.Column('photo_key', sa.String(length=200), nullable=False),
    sa.Column('directory_visible', sa.Boolean(), nullable=False),
    sa.Column('willing_host', sa.Boolean(), nullable=False),
    sa.Column('willing_present', sa.Boolean(), nullable=False),
    sa.Column('willing_organize', sa.Boolean(), nullable=False),
    sa.Column('norms_accepted_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('removal_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.String(length=32), nullable=True),
    sa.Column('sent_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_id', sa.String(length=32), nullable=True),
    sa.Column('redeemed_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_table('email_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_kind'), 'email_messages', ['kind'], unique=False)
    op.create_index(op.f('ix_email_messages_status'), 'email_messages', ['status'], unique=False)
    op.create_table('members',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invited_via_id', sa.String(length=32), nullable=True),
    sa.Column('approved_by_id', sa.String(length=32), nullable=True),
    sa.Column('approved_at', app.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('welcome_cohost', sa.String(length=120), nullable=False),
    sa.Column('needs_followup', sa.Boolean(), nullable=False),
    sa.Column('followup_note', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_via_id'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_email_messages_status'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_kind'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_table('removal_requests')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_private_notes_subject_id'), table_name='private_notes')
    op.drop_table('private_notes')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_referrer'), table_name='applications')
    op.drop_index(op.f('ix_applications_email'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_login_codes_email'), table_name='login_codes')
    op.drop_table('login_codes')
    op.drop_table('events')
    # ### end Alembic commands ###
